version: '3'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-net

  redis:
    image: redis:alpine
    networks:
      - app-net

  vote:
    build: ./vote
    ports:
      - "5000:80"
    depends_on:
      - redis
      - postgres
    networks:
      - app-net

  worker:
    build: ./worker
    depends_on:
      - redis
      - postgres
    networks:
      - app-net

  result:
    build: ./result
    ports:
      - "4000:4000"
    depends_on:
      - redis
      - postgres
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
